services:
  - type: web
    name: fakeit-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://fakeit-frontend.vercel.app
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_sK9dx2BGqpbQ@ep-patient-wave-a14112fy-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
